#ifndef _CORAL_NOTIFICATION_H_
#define _CORAL_NOTIFICATION_H_

#include <stddef.h>

extern const char *CORAL_NOTIFICATION_OBJECT_DESTROYED;
extern const char *CORAL_NOTIFICATION_CONTAINER_INCREASED;
extern const char *CORAL_NOTIFICATION_CONTAINER_DECREASED;
extern const char *CORAL_NOTIFICATION_CONTAINER_CHANGED;

#endif /* _CORAL_NOTIFICATION_H_ */
